### PR TITLE
Fix module references

### LINKED ISSUE #14: Fix Packaging
This library is declared as a dependency by 'simplemde-markdown-editor', which is CommonJS compatible, except when it isn't, because src/js/spell-checker.js assumes there is a CodeMirror global, and that breaks the package 'simplemde-markdown-editor'.

I was going to make a fork, then a pull request later, but this guy [@universome ](https://github.com/universome/codemirror-spell-checker), has already fixed it...

### PR DESCRIPTION
**Pull request by WebCloud**
Fix the reference to CodeMirror by instead of trying to use a global,
require the module. Also fix the usage of Typo, using the same
principles. This fixes #14 for good.

### CODE REVIEW

**Comment by WesCossick** [comment]
Can you update the PR so that it doesn't remove all the tabs from empty lines? This will both keep the code styling correct and will ensure the "Files changed" tab isn't too confusing.

**Comment by WebCloud** [comment]
I am sorry, I forgot my default setup on Atom and have not checked the full diff.

**Comment by WebCloud** [comment]
The commit is now fixed with only the actual fixes.

**Comment by kyeotic** [comment]
@WesCossick Any update on this? It would be really nice to have this fixed

**Comment by WesCossick** [comment]
Last step, @WebCloud can you compare this same PR again the `development` branch? All changes must go into the development branch before being merged into the master. I'm going to close this PR until that happens.

**Pull request closed without merging**
